(
	echo "// autogenerated by deploy.sh"
	echo "#define MINUTES  $(date +%M)"
	echo "#define HOURS    $(date +%k)"
	echo "#define SECONDS  $(date +%S)"
) > src/current_time.h

ino build && ino upload

rm src/current_time.h
